version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-server
    environment:
      - CASSANDRA_DC=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    ports:
      - "9042:9042"
    networks:
      - yachak-network

networks:
  yachak-network:
    driver: bridge
